import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { defineConfig, loadEnv } from 'vite'
import { configDefaults } from 'vitest/config'
import react from '@vitejs/plugin-react'

// A production deploy must know where the API is. Without VITE_API_BASE_URL
// the app would quietly call http://127.0.0.1:8001 from every visitor's
// browser, so a Vercel production build stops here instead. Preview builds
// and local development are left alone.
export function checkProductionEnv(env, vercelEnv, warn = console.warn) {
  if (vercelEnv !== 'production') return
  if (!env.VITE_API_BASE_URL) {
    throw new Error(
      'VITE_API_BASE_URL is not set for this production build. Set it in Vercel → Settings → ' +
        'Environment Variables (Production) to the backend URL, then redeploy.',
    )
  }
  if (!env.VITE_SENTRY_DSN) {
    warn('Warning: VITE_SENTRY_DSN is not set, so frontend errors in production will not be reported.')
  }
}

// The body font is only discovered once the app has rendered, after the
// main script has downloaded and run. Preloading it from index.html starts
// that download straight away, so text appears in Inter sooner (F-2).
export const PRELOADED_FONT = 'inter-latin-wght-normal'

export function fontPreloadTags(bundle = {}, base = '/') {
  const file = Object.keys(bundle).find((name) => name.includes(PRELOADED_FONT) && name.endsWith('.woff2'))
  if (!file) return []
  return [{
    tag: 'link',
    attrs: { rel: 'preload', as: 'font', type: 'font/woff2', href: `${base}${file}`, crossorigin: '' },
    injectTo: 'head',
  }]
}

function preloadBodyFont() {
  let base = '/'
  return {
    name: 'housemaster-preload-body-font',
    apply: 'build',
    configResolved(config) {
      base = config.base
    },
    transformIndexHtml(html, ctx) {
      return fontPreloadTags(ctx.bundle, base)
    },
  }
}

// Offline start (installable app). The service worker keeps the page, the
// scripts and styles it needs to start, the icons and the body font on the
// phone, so the app opens with no signal. Everything else under /assets/
// (the PDF viewer, other fonts) is kept the first time it's used. The API is
// on another site and is never touched: data always comes from the server.
export const APP_ICONS = ['icons/icon-192.png', 'icons/icon-512.png', 'icons/apple-touch-icon.png',
  'housemaster-logo.png', 'housemaster-mark-light.png']

export function precacheList(bundle = {}, base = '/') {
  const out = new Set([base, `${base}index.html`, `${base}manifest.webmanifest`, ...APP_ICONS.map((i) => base + i)])
  const visit = (name) => {
    const item = bundle[name]
    if (!item || item.type !== 'chunk' || out.has(base + name)) return
    out.add(base + name)
    for (const dep of item.imports || []) visit(dep)
    for (const css of item.viteMetadata?.importedCss || []) out.add(base + css)
  }
  for (const [name, item] of Object.entries(bundle)) {
    if (item.type === 'chunk' && item.isEntry) visit(name)
  }
  for (const [name, item] of Object.entries(bundle)) {
    if (item.type !== 'asset') continue
    if (name.endsWith('.css') || (name.includes(PRELOADED_FONT) && name.endsWith('.woff2'))) out.add(base + name)
  }
  return [...out]
}

// `extra` is anything else whose change should replace the stored copy
// (the page itself, the manifest).
export function serviceWorkerSource(files, extra = '') {
  const version = createHash('sha256').update(files.join('\n')).update(extra).digest('hex').slice(0, 12)
  return `// Generated by vite.config.js at build time. Do not edit.
const CACHE = 'housemaster-${version}'
const PRECACHE = ${JSON.stringify(files)}
const PAGE_TIMEOUT_MS = 4000

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

// Old copies go once no open tab uses them any more.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('housemaster-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  if (request.mode === 'navigate') {
    event.respondWith(page(request))
  } else if (url.pathname.startsWith('/assets/') || PRECACHE.includes(url.pathname)) {
    event.respondWith(stored(request))
  }
})

// The page: the newest from the network when the signal answers within a
// few seconds, otherwise the copy on the phone.
async function page(request) {
  const cache = await caches.open(CACHE)
  try {
    const response = await Promise.race([
      fetch(request),
      new Promise((_, reject) => setTimeout(() => reject(new Error('slow')), PAGE_TIMEOUT_MS)),
    ])
    if (response.ok) cache.put('/index.html', response.clone())
    return response
  } catch {
    return (await cache.match('/index.html')) || (await cache.match('/')) || Response.error()
  }
}

// Scripts, styles, fonts and icons never change under the same name, so the
// copy on the phone is used first.
async function stored(request) {
  const cache = await caches.open(CACHE)
  const hit = await cache.match(request)
  if (hit) return hit
  const response = await fetch(request)
  if (response.ok && new URL(request.url).pathname.startsWith('/assets/')) cache.put(request, response.clone())
  return response
}
`
}

function serviceWorker() {
  let base = '/'
  let root = process.cwd()
  return {
    name: 'housemaster-service-worker',
    apply: 'build',
    configResolved(config) {
      base = config.base
      root = config.root
    },
    writeBundle(options, bundle) {
      const html = bundle['index.html']?.source || ''
      let manifest = ''
      try {
        manifest = readFileSync(join(root, 'public', 'manifest.webmanifest'), 'utf8')
      } catch {
        // no manifest: the worker still works
      }
      writeFileSync(join(options.dir, 'sw.js'), serviceWorkerSource(precacheList(bundle, base), String(html) + manifest))
    },
  }
}

export default defineConfig(({ mode }) => {
  checkProductionEnv(loadEnv(mode, process.cwd(), 'VITE_'), process.env.VERCEL_ENV)
  return {
    plugins: [react(), preloadBodyFont(), serviceWorker()],
    server: {
      port: 5173,
    },
    test: {
      environment: 'jsdom',
      // e2e/ holds the Playwright smoke tests (their own package and runner).
      exclude: [...configDefaults.exclude, 'e2e/**'],
      setupFiles: ['./src/test/setup.js'],
    },
  }
})
