import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { defineConfig, loadEnv } from 'vite'
import { configDefaults } from 'vitest/config'
import react from '@vitejs/plugin-react'

// A production deploy must know where the API is. Without VITE_API_BASE_URL
// the app would quietly call http://127.0.0.1:8001 from every visitor's
// browser, so a Vercel production build stops here instead. Preview builds
// and local development are left alone.
export function checkProductionEnv(env, vercelEnv, warn = console.warn) {
  if (vercelEnv !== 'production') return
  if (!env.VITE_API_BASE_URL) {
    throw new Error(
      'VITE_API_BASE_URL is not set for this production build. Set it in Vercel → Settings → ' +
        'Environment Variables (Production) to the backend URL, then redeploy.',
    )
  }
  if (!env.VITE_SENTRY_DSN) {
    warn('Warning: VITE_SENTRY_DSN is not set, so frontend errors in production will not be reported.')
  }
}

// The body font is only discovered once the app has rendered, after the
// main script has downloaded and run. Preloading it from index.html starts
// that download straight away, so text appears in Inter sooner (F-2).
export const PRELOADED_FONT = 'inter-latin-wght-normal'

export function fontPreloadTags(bundle = {}, base = '/') {
  const file = Object.keys(bundle).find((name) => name.includes(PRELOADED_FONT) && name.endsWith('.woff2'))
  if (!file) return []
  return [{
    tag: 'link',
    attrs: { rel: 'preload', as: 'font', type: 'font/woff2', href: `${base}${file}`, crossorigin: '' },
    injectTo: 'head',
  }]
}

function preloadBodyFont() {
  let base = '/'
  return {
    name: 'housemaster-preload-body-font',
    apply: 'build',
    configResolved(config) {
      base = config.base
    },
    transformIndexHtml(html, ctx) {
      return fontPreloadTags(ctx.bundle, base)
    },
  }
}

// The service worker is only for phone and browser notifications (push.js).
// HouseMaster is online only: the worker keeps no copy of the app, and
// removes the copies the old offline version left on phones, so everyone
// always gets the newest app from the internet.
export function serviceWorkerSource(extra = '') {
  const version = createHash('sha256').update(extra).digest('hex').slice(0, 12)
  return `// Generated by vite.config.js at build time. Do not edit. Version ${version}.
// Online only: no copy of the app is kept here; this worker just shows notifications.

self.addEventListener('install', () => self.skipWaiting())

// Remove the copies the old offline version kept, then take over open tabs.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('housemaster-')).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// Phone and browser notifications (src/push.js): a short notice from the
// school's server. A tap opens HouseMaster, never another site.
self.addEventListener('push', (event) => {
  let data = {}
  try { data = event.data ? event.data.json() : {} } catch { data = {} }
  event.waitUntil(self.registration.showNotification(String(data.title || 'HouseMaster'), {
    body: String(data.body || 'There is something new in HouseMaster.'),
    icon: '/icons/icon-192.png',
    data: { url: typeof data.url === 'string' ? data.url : '/' },
  }))
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  let url = new URL('/', self.location.origin)
  try { url = new URL(event.notification.data?.url || '/', self.location.origin) } catch { /* keep the home page */ }
  if (url.origin !== self.location.origin) url = new URL('/', self.location.origin)
  event.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((tabs) => {
    const open = tabs.find((t) => new URL(t.url).origin === self.location.origin)
    return open ? open.focus().then((t) => t && t.navigate ? t.navigate(url.href) : t) : self.clients.openWindow(url.href)
  }))
})
`
}

function serviceWorker() {
  return {
    name: 'housemaster-service-worker',
    apply: 'build',
    writeBundle(options, bundle) {
      writeFileSync(join(options.dir, 'sw.js'), serviceWorkerSource(String(bundle['index.html']?.source || '')))
    },
  }
}

export default defineConfig(({ mode }) => {
  checkProductionEnv(loadEnv(mode, process.cwd(), 'VITE_'), process.env.VERCEL_ENV)
  return {
    plugins: [react(), preloadBodyFont(), serviceWorker()],
    server: {
      port: 5173,
    },
    test: {
      environment: 'jsdom',
      // e2e/ holds the Playwright smoke tests (their own package and runner).
      exclude: [...configDefaults.exclude, 'e2e/**'],
      setupFiles: ['./src/test/setup.js'],
    },
  }
})
